// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type User struct {
	ID       int64  `db:"id" json:"ID"`
	Email    string `db:"email" json:"Email"`
	FullName string `db:"full_name" json:"FullName"`
	Password string `db:"password" json:"Password"`
}
